//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySozlukWebGit.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeySet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeySet()
        {
            this.CommentSet = new HashSet<CommentSet>();
        }
    
        public int Id { get; set; }
        public string Word { get; set; }
        public int Publishing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentSet> CommentSet { get; set; }
    }
}
